language: node_js
# node version is set by .nvmrc
git:
  submodules: false
stages:
  - develop
  - release
before_install:
  - echo "installing dependencies..."
  - yarn install
jobs:
  include:
    - if: branch = master
    - if: branch = release
    - if: branch = test-ci
      name: "Release"
      branches:
      only:
        - release
      after_success:
        - yarn semantic-release