language: node_js
# node version is set by .nvmrc
git:
  submodules: false
before_install:
  - echo "installing dependencies..."
  - yarn install
stages:
  - stage: test
    name: "Unit-tests"
  - stage: release
    name: "Semantic release"
    script: skip
    after_success:
      - yarn semantic-release
    if: branch = master || branch = release || branch = test-ci