language: node_js
# node version is set by .nvmrc
cache:
  yarn: true
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo "installing dependencies..."
  - yarn install
stages:
  - stage: test
    name: "Unit-tests"
  - stage: release
    name: "Semantic release"
    script: skip
    after_success:
      - yarn semantic-release
    if: branch = master || branch = release || branch = test-ci