language: node_js
# node version is set by .nvmrc
cache:
  yarn: true
  npm: true
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - npm i -g npm@6.9.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
stages:
  - name: validate
  - name: tests
  - name: release
    if: branch = release AND NOT tag AND type NOT IN (pull_request)
jobs:
  include:
    - stage: validate
      name: lint code
      install:
        - yarn
      script: yarn eslint '*.js'
    - stage: validate
      name: validate MESG file
      install:
        - "[ ! -e /usr/local/bin/mesg-core ] && bash <(curl -fsSL https://mesg.com/install)"
      script: mesg-core service validate
      after_script:
        - mesg-core stop
    - stage: tests
      name: integration tests
      install:
        - "[ ! -e /usr/local/bin/mesg-core ] && bash <(curl -fsSL https://mesg.com/install)"
      before_script:
        - mesg-core service deploy
        - mesg-core service start com.mesg.pusher
      script: yarn test
      after_script:
        - mesg-core stop
    - stage: release
      name: semantic release
      install:
        - yarn
      script: yarn semantic-release --branch $TRAVIS_BRANCH
matrix:
  fast_finish: true