language: node_js
# node version is set by .nvmrc
cache:
  yarn: true
  npm: true
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - echo "updating NPM..."
  - npm i -g npm@6.9.0
  - echo "updating Yarn..."
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo "installing MESG..."
  - bash <(curl -fsSL https://mesg.com/install)
  - mesg-core start
  - echo "installing dependencies..."
  - yarn
stages:
  - name: install
  - name: validate
    install: true
  - name: tests
    install: true
    skip_cleanup: true
  - name: tests
    install: true
    if: branch = release AND NOT tag AND type NOT IN (pull_request)
jobs:
  include:
    - stage: install
    - stage: validate
      name: lint code
      script: yarn eslint '*.js'
    - stage: validate
      name: validate MESG file
      script: mesg-core service validate
    - stage: tests
      before_script:
        - mesg-core service deploy
        - mesg-core service start com.mesg.pusher
      script: yarn test || travis_terminate 1;
    - stage: release
      script: yarn semantic-release --branch $TRAVIS_BRANCH
matrix:
  fast_finish: true