language: node_js
# node version is set by .nvmrc
cache:
  yarn: true
  npm: true
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - npm i -g npm@6.9.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn
  - system=$(uname -s | tr A-Z a-z)
  - machine=$(uname -m)
stages:
  - name: validate
  - name: tests
  - name: release
    if: branch = release AND NOT tag AND type NOT IN (pull_request)
jobs:
  include:
    - stage: validate
      name: lint code
      script: yarn eslint '*.js'
    - stage: validate
      name: validate MESG file
      install:
        - bash <(curl -fsSL https://mesg.com/install)
      before_script:
        - mesg-core start
      script: mesg-core service validate
    - stage: tests
      name: integration tests
      install:
        - bash <(curl -fsSL https://mesg.com/install)
      before_script:
        - mesg-core start
        - sleep 3
        - mesg-core service deploy
        - mesg-core service start com.mesg.pusher
      script: yarn test
    - stage: release
      name: semantic release
      script: yarn semantic-release --branch $TRAVIS_BRANCH
matrix:
  fast_finish: true