language: node_js
# node version is set by .nvmrc
cache:
  yarn: true
  npm: true
  directories:
    - node_modules
git:
  submodules: false
before_install:
  - echo "updating NPM..."
  - npm i -g npm@6.9.0
  - echo "updating Yarn..."
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo "installing dependencies..."
  - yarn
jobs:
  include:
    - stage: lint
      script: yarn eslint '*.js'
    - stage: validate
      before_script: mesg-core start
      script: mesg-core service validate
      image: mesg/core
    - stage: tests
      install: true
      script: yarn test || travis_terminate 1;
    - stage: release
      if: branch = release AND NOT tag AND type NOT IN (pull_request)
      install: true
      script: yarn semantic-release --branch $TRAVIS_BRANCH
matrix:
  fast_finish: true